spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_teaching_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
app:
  signing-secret:tes123