spring:
  profiles:
    active: dev
  datasource:
    url: ${CTS_DATASOURCE_URL}
    username: ${CTS_DATASOURCE_USERNAME}
    password: ${CTS_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379
app:
  signing-secret: ${SIGNING_SECRET}
  file-save-path: ${FILE_SAVE_PATH}